"""add email to students

Revision ID: b8c27f350e2e
Revises: 791279dd0760
Create Date: 2025-05-24 00:49:00.892346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c27f350e2e'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
